### ISSUE TITLE
Change title from "GraphQL client for all platforms" to a list of the actual platforms

### ISSUE THREAD

**Issue by stubailo** [apollostack/dev.apollodata.com#13]
Will be helpful in Google search results. @danahmadi what do you think?

**Comment by danahmadi** [comment]
Will the number of platforms fit in a headline sentence? It feels like if there are a lot then maybe this section doesn't belong in the headline at all (and should be a table)

**Comment by stubailo** [comment]
Maybe "GraphQL client for React, Angular, iOS, Android, and more."

**Comment by danahmadi** [comment]
sgtm-- changed
